package
{
   import flash.Boot;
   import flash.Lib;
   import flash.display.MovieClip;
   import flash.geom.ColorTransform;
   import flash.geom.Matrix;
   import haxe.Unserializer;
   import haxe.io.Bytes;
   import haxe.§h\x05\x02\x02§;
   import mt.data.Mods;
   import pix.Element;
   import tora.Code;
   import tora.Protocol;
   
   public dynamic class §\x0fnR\x11\x03§ extends Boot
   {
       
      
      public function §\x0fnR\x11\x03§()
      {
         if(Boot.skip_constructor)
         {
            return;
         }
         super();
         if(Lib.current == null)
         {
            Lib.current = this;
         }
         start();
      }
      
      override public function init() : void
      {
         var _loc2_:* = null as Array;
         var _loc1_:* = Date;
         _loc1_.now = function():*
         {
            return new Date();
         };
         _loc1_.fromTime = function(param1:*):Date
         {
            var _loc2_:Date = new Date();
            _loc2_.setTime(param1);
            return _loc2_;
         };
         _loc1_.fromString = function(param1:String):Date
         {
            var _loc2_:* = null as Array;
            var _loc3_:* = null as Date;
            var _loc4_:* = null as Array;
            var _loc5_:* = null as Array;
            switch(param1.length)
            {
               default:
               default:
               default:
               default:
               default:
               default:
               default:
               default:
                  Boot.lastError = new Error();
                  throw "Invalid date format : " + param1;
               case 8:
               default:
                  _loc2_ = param1.split(":");
                  _loc3_ = new Date();
                  _loc3_.setTime(0);
                  _loc3_.setUTCHours(_loc2_[0]);
                  _loc3_.setUTCMinutes(_loc2_[1]);
                  _loc3_.setUTCSeconds(_loc2_[2]);
                  return _loc3_;
               case 10:
               default:
               default:
               default:
               default:
               default:
               default:
               default:
               default:
                  _loc2_ = param1.split("-");
                  return new Date(int(_loc2_[0]),_loc2_[1] - 1,int(_loc2_[2]),0,0,0);
               case 19:
                  _loc2_ = param1.split(" ");
                  _loc4_ = _loc2_[0].split("-");
                  _loc5_ = _loc2_[1].split(":");
                  return new Date(int(_loc4_[0]),_loc4_[1] - 1,int(_loc4_[2]),int(_loc5_[0]),int(_loc5_[1]),int(_loc5_[2]));
            }
         };
         _loc1_.prototype["toString"] = function():String
         {
            var _loc1_:Date = this;
            var _loc2_:int = int(_loc1_.getMonth()) + 1;
            var _loc3_:int = int(_loc1_.getDate());
            var _loc4_:int = int(_loc1_.getHours());
            var _loc5_:int = int(_loc1_.getMinutes());
            var _loc6_:int = int(_loc1_.getSeconds());
            return int(_loc1_.getFullYear()) + "-" + (_loc2_ < 10?"0" + _loc2_:"" + _loc2_) + "-" + (_loc3_ < 10?"0" + _loc3_:"" + _loc3_) + " " + (_loc4_ < 10?"0" + _loc4_:"" + _loc4_) + ":" + (_loc5_ < 10?"0" + _loc5_:"" + _loc5_) + ":" + (_loc6_ < 10?"0" + _loc6_:"" + _loc6_);
         };
         Math.NaN = Number(Number.NaN);
         Math.NEGATIVE_INFINITY = Number(Number.NEGATIVE_INFINITY);
         Math.POSITIVE_INFINITY = Number(Number.POSITIVE_INFINITY);
         Math.isFinite = function(param1:Number):Boolean
         {
            return isFinite(param1);
         };
         Math.isNaN = function(param1:Number):Boolean
         {
            return isNaN(param1);
         };
         if(!Bonus.init__)
         {
            Bonus.init__ = true;
            Bonus.DATA = [{
               "id":BonusType.__bonusPetard,
               "weight":24
            },{
               "id":BonusType.__bonusScissors,
               "weight":24
            },{
               "id":BonusType.__bonusChest,
               "weight":12
            },{
               "id":BonusType.__bonusFlute,
               "weight":6
            },{
               "id":BonusType.__bonusGuitare,
               "weight":4
            },{
               "id":BonusType.__bonusTrompette,
               "weight":50
            },{
               "id":BonusType.__bonusBouee,
               "weight":6
            },{
               "id":BonusType.__bonusPilule,
               "weight":10
            },{
               "id":BonusType.__bonusFruitibarrePetit,
               "weight":8
            },{
               "id":BonusType.__bonusFruitibarreGrand,
               "weight":100
            },{
               "id":BonusType.§;\x12F\x03§,
               "weight":100
            },{
               "id":BonusType.__bonusAllumettes,
               "weight":6
            },{
               "id":BonusType.__bonusSacDeGraines,
               "weight":4
            },{
               "id":BonusType.__bonusCloche,
               "weight":1
            },{
               "id":BonusType.__bonusBouclierRouge,
               "weight":6
            },{
               "id":BonusType.__bonusTShirt,
               "weight":1
            },{
               "id":BonusType.__bonusCollierRouge,
               "weight":2
            },{
               "id":BonusType.§\x1fE s\x02§,
               "weight":2
            },{
               "id":BonusType.__bonusCollierBleu,
               "weight":2
            },{
               "id":BonusType.__bonusCard,
               "weight":3
            },{
               "id":BonusType.§tsr\x03§,
               "weight":0
            }];
         }
         if(!Codec.init__)
         {
            Codec.init__ = true;
            Codec.types = new Hash();
            Codec.protocols = [];
         }
         if(!Cs.init__)
         {
            Cs.init__ = true;
            Cs.§\t;\x1cH\x02§ = [_CardType.POO,_CardType.SQUIRREL,_CardType.__RUNE_FLORE,_CardType.PIN,_CardType.HORMONES];
         }
         if(!__fruitList.init__)
         {
            __fruitList.init__ = true;
            __fruitList.LIST = [{
               "score":8,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":5,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Apple]
            },{
               "score":7,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":1,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":9,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":6,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":15,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":105,
               "tags":[_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":7,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":25,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":22,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":128,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":15,
               "vit":20,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":256,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.§!}5\t\x01§,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":11,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":63,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":15,
               "vit":30,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":84,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":8,
               "cal":1,
               "vit":15,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":21,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.§1\x17E\x0e\x01§]
            },{
               "score":10,
               "cal":15,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":42,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":15,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":44,
               "tags":[_x_TYPE.Nut]
            },{
               "score":10,
               "cal":5,
               "vit":5,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":53,
               "tags":[_x_TYPE.Sugar,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":10,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Long]
            },{
               "score":15,
               "cal":15,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":115,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":40,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":36,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Nut,_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":279,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Blue,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":57,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":112,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Nut,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":26,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":15,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":29,
               "tags":[_x_TYPE.Nut,_x_TYPE.Small]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":3,
               "tags":[_x_TYPE.Small,_x_TYPE.Green,_x_TYPE.Blue,_x_TYPE.Poire]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":70,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":8,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":0,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":28,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":3,
               "\x0e-EY\x01":1,
               "rank":35,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Flower]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":110,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Red]
            },{
               "score":10,
               "cal":2,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":17,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Green,_x_TYPE.Courge]
            },{
               "score":15,
               "cal":30,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":113,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":79,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Green,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":14,
               "tags":[_x_TYPE.Sugar,_x_TYPE.§x_(\x02§,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":5,
               "vit":15,
               "sta":30,
               "\x0e-EY\x01":1,
               "rank":48,
               "tags":[_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":153,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":3,
               "\x0e-EY\x01":1,
               "rank":209,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Poire,_x_TYPE.Pink]
            },{
               "score":15,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":23,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":194,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.§!}5\t\x01§,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":4,
               "tags":[_x_TYPE.Nut,_x_TYPE.Small]
            },{
               "score":10,
               "cal":5,
               "vit":15,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":90,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":13,
               "tags":[_x_TYPE.Small]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":37,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":46,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":199,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small]
            },{
               "score":10,
               "cal":20,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":74,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":0,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":43,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Leaf,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":10,
               "vit":30,
               "sta":30,
               "\x0e-EY\x01":1,
               "rank":51,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":15,
               "cal":10,
               "vit":15,
               "sta":3,
               "\x0e-EY\x01":1,
               "rank":49,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small]
            },{
               "score":5,
               "cal":15,
               "vit":30,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":124,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":30,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":20,
               "tags":[_x_TYPE.Small,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":120,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":20,
               "cal":40,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":130,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":65,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":131,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":16,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":0,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":135,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":12,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":45,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Orange,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":5,
               "vit":0,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":140,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":20,
               "cal":20,
               "vit":50,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":300,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":144,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":10,
               "vit":50,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":148,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Small]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":76,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":30,
               "\x0e-EY\x01":1,
               "rank":159,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":161,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red]
            },{
               "score":10,
               "cal":10,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":192,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":15,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":170,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":247,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":15,
               "vit":20,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":39,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green,_x_TYPE.Long,_x_TYPE.Courge]
            },{
               "score":7,
               "cal":0,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":118,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":0,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":232,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":179,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":183,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":12,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Orange]
            },{
               "score":30,
               "cal":15,
               "vit":10,
               "sta":4,
               "\x0e-EY\x01":1,
               "rank":98,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":5,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":177,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":15,
               "cal":20,
               "vit":20,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":30,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Apple]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":24,
               "tags":[_x_TYPE.§x_(\x02§,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":218,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":68,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":5,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":222,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":31,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":19,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":0,
               "sta":100,
               "\x0e-EY\x01":1,
               "rank":224,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":-10,
               "cal":15,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":160,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":231,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":34,
               "tags":[_x_TYPE.Sugar,_x_TYPE.§x_(\x02§,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":236,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":12,
               "cal":10,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":295,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":5,
               "vit":25,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":238,
               "tags":[_x_TYPE.Alien,_x_TYPE.Blue,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":15,
               "vit":40,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":276,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien]
            },{
               "score":10,
               "cal":0,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":86,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":96,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":251,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Flower]
            },{
               "score":15,
               "cal":10,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":241,
               "tags":[_x_TYPE.Red,_x_TYPE.Flower,_x_TYPE.§!}5\t\x01§,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":0,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":203,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":59,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Blue]
            },{
               "score":-10,
               "cal":20,
               "vit":5,
               "sta":30,
               "\x0e-EY\x01":2,
               "rank":93,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":100,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":263,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":260,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Alien]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":264,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":5,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":268,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":56,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Long,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":168,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":-10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":88,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":3,
               "vit":10,
               "sta":50,
               "\x0e-EY\x01":1,
               "rank":167,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":5,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":262,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":15,
               "cal":15,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":285,
               "tags":[_x_TYPE.§!}5\t\x01§,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":237,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":281,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Nut]
            },{
               "score":10,
               "cal":20,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":292,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":139,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":155,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":142,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":-15,
               "cal":0,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":141,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Alien]
            },{
               "score":-10,
               "cal":15,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":270,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":204,
               "tags":[_x_TYPE.Nut]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":271,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Yellow]
            },{
               "score":12,
               "cal":15,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":152,
               "tags":[_x_TYPE.Nut,_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":173,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Poire]
            },{
               "score":-10,
               "cal":5,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":156,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":149,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":228,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":5,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":138,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":216,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Yellow,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":272,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Red]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":198,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Green,_x_TYPE.Alien]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":296,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":5,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":273,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":274,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":211,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":255,
               "tags":[_x_TYPE.Green,_x_TYPE.§!}5\t\x01§]
            },{
               "score":15,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":299,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":250,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":277,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green,_x_TYPE.§!}5\t\x01§]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":283,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.§!}5\t\x01§,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":107,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":286,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.§!}5\t\x01§]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":77,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Long,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":193,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":164,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Pink]
            },{
               "score":7,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":282,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Red,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":15,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":288,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":15,
               "cal":15,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":290,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Pink]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":188,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge]
            },{
               "score":15,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":294,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":242,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":0,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":293,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":163,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Long,_x_TYPE.Blue]
            },{
               "score":5,
               "cal":2,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":67,
               "tags":[_x_TYPE.Nut,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":244,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":5,
               "vit":5,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":212,
               "tags":[_x_TYPE.Courge,_x_TYPE.Leaf,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":297,
               "tags":[_x_TYPE.Sugar,_x_TYPE.§x_(\x02§,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":225,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":254,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":195,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":0,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":185,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":35,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":172,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":207,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge]
            },{
               "score":-15,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":298,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":102,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":190,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":100,
               "\x0e-EY\x01":1,
               "rank":245,
               "tags":[_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":239,
               "tags":[_x_TYPE.Flower,_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":18,
               "tags":[_x_TYPE.Green,_x_TYPE.Small,_x_TYPE.Poire]
            },{
               "score":8,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":73,
               "tags":[_x_TYPE.Small,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Sugar]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":182,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Green]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":259,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Green,_x_TYPE.Long,_x_TYPE.Courge]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":8,
               "rank":230,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":7,
               "cal":20,
               "vit":5,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":158,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire]
            },{
               "score":15,
               "cal":5,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":89,
               "tags":[_x_TYPE.Flower,_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":275,
               "tags":[_x_TYPE.Sugar,_x_TYPE.§!}5\t\x01§]
            },{
               "score":15,
               "cal":20,
               "vit":50,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":214,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":81,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Blue,_x_TYPE.Sugar]
            },{
               "score":-10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":72,
               "tags":[_x_TYPE.Small,_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Red,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":217,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Courge,_x_TYPE.Blue]
            },{
               "score":30,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":82,
               "tags":[_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Red]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":126,
               "tags":[_x_TYPE.Green,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":75,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":129,
               "tags":[_x_TYPE.Small,_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":25,
               "cal":20,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":215,
               "tags":[_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":210,
               "tags":[_x_TYPE.Nut]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":71,
               "tags":[_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":32,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":162,
               "tags":[_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Small,_x_TYPE.Sugar]
            },{
               "score":5,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":20,
               "rank":2,
               "tags":[_x_TYPE.Long,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":2,
               "rank":80,
               "tags":[_x_TYPE.Nut,_x_TYPE.Green]
            },{
               "score":15,
               "cal":10,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":58,
               "tags":[_x_TYPE.Yellow,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":50,
               "tags":[_x_TYPE.Small,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":15,
               "\x0e-EY\x01":2,
               "rank":147,
               "tags":[_x_TYPE.Flower,_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Sugar]
            },{
               "score":5,
               "cal":10,
               "vit":10,
               "sta":50,
               "\x0e-EY\x01":3,
               "rank":60,
               "tags":[_x_TYPE.Small,_x_TYPE.Leaf]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":2,
               "rank":91,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Orange,_x_TYPE.Yellow]
            },{
               "score":25,
               "cal":25,
               "vit":25,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":154,
               "tags":[_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":52,
               "tags":[_x_TYPE.Green,_x_TYPE.Long]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":8,
               "rank":101,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":30,
               "cal":15,
               "vit":20,
               "sta":7,
               "\x0e-EY\x01":10,
               "rank":171,
               "tags":[_x_TYPE.Small,_x_TYPE.Red,_x_TYPE.Leaf]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":15,
               "\x0e-EY\x01":2,
               "rank":175,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Courge]
            },{
               "score":5,
               "cal":20,
               "vit":25,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":151,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":133,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.Sugar]
            },{
               "score":40,
               "cal":10,
               "vit":50,
               "sta":10,
               "\x0e-EY\x01":12,
               "rank":197,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":27,
               "tags":[_x_TYPE.Green]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":186,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Yellow]
            },{
               "score":5,
               "cal":5,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":97,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":200,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":20,
               "vit":20,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":41,
               "tags":[_x_TYPE.Small,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":246,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":109,
               "tags":[_x_TYPE.§!}5\t\x01§,_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":30,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":184,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":15,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":143,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":5,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":116,
               "tags":[_x_TYPE.§x_(\x02§,_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":20,
               "cal":0,
               "vit":30,
               "sta":5,
               "\x0e-EY\x01":2,
               "rank":234,
               "tags":[]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":122,
               "tags":[_x_TYPE.Leaf,_x_TYPE.§!}5\t\x01§,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":30,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":106,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":50,
               "cal":10,
               "vit":0,
               "sta":7,
               "\x0e-EY\x01":12,
               "rank":64,
               "tags":[]
            },{
               "score":20,
               "cal":15,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":249,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":2,
               "rank":125,
               "tags":[_x_TYPE.§!}5\t\x01§,_x_TYPE.Long,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":20,
               "cal":20,
               "vit":5,
               "sta":20,
               "\x0e-EY\x01":2,
               "rank":266,
               "tags":[_x_TYPE.Nut,_x_TYPE.Sugar]
            },{
               "score":5,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":267,
               "tags":[]
            },{
               "score":30,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":253,
               "tags":[_x_TYPE.Small,_x_TYPE.§!}5\t\x01§,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":50,
               "sta":7,
               "\x0e-EY\x01":25,
               "rank":85,
               "tags":[_x_TYPE.Small,_x_TYPE.Green,_x_TYPE.§!}5\t\x01§,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":20,
               "vit":20,
               "sta":100,
               "\x0e-EY\x01":5,
               "rank":248,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge,_x_TYPE.Sugar]
            },{
               "score":-10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":123,
               "tags":[_x_TYPE.Green,_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":78,
               "tags":[_x_TYPE.Small,_x_TYPE.Alien,_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":5,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":223,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":257,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":99,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":4,
               "rank":284,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Long,_x_TYPE.Blue]
            },{
               "score":-20,
               "cal":10,
               "vit":20,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":187,
               "tags":[_x_TYPE.Poire,_x_TYPE.Red,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":205,
               "tags":[_x_TYPE.Green,_x_TYPE.Courge,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":258,
               "tags":[_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Red,_x_TYPE.§!}5\t\x01§,_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":181,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Pink]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":3,
               "rank":227,
               "tags":[_x_TYPE.Alien,_x_TYPE.Courge,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":50,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":10,
               "rank":15,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":1,
               "rank":261,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":25,
               "cal":30,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":269,
               "tags":[]
            },{
               "score":-10,
               "cal":0,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":189,
               "tags":[_x_TYPE.Courge,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":191,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":178,
               "tags":[_x_TYPE.Nut,_x_TYPE.Pink]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":20,
               "\x0e-EY\x01":2,
               "rank":265,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":289,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien]
            },{
               "score":10,
               "cal":5,
               "vit":15,
               "sta":5,
               "\x0e-EY\x01":2,
               "rank":291,
               "tags":[_x_TYPE.Flower,_x_TYPE.Leaf,_x_TYPE.Red]
            },{
               "score":-10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":176,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf]
            },{
               "score":5,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":208,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":5,
               "cal":10,
               "vit":30,
               "sta":5,
               "\x0e-EY\x01":5,
               "rank":146,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":60,
               "cal":30,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":30,
               "rank":54,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":5,
               "cal":5,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":33,
               "tags":[_x_TYPE.Small,_x_TYPE.Leaf]
            },{
               "score":40,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":8,
               "rank":229,
               "tags":[_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Blue]
            },{
               "score":50,
               "cal":0,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":278,
               "tags":[_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":280,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Sugar]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":104,
               "tags":[_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":38,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":-25,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":4,
               "rank":47,
               "tags":[_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":20,
               "cal":15,
               "vit":20,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":117,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Alien,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":252,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":4,
               "rank":235,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Red]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":201,
               "tags":[_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":25,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":221,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":243,
               "tags":[_x_TYPE.Blue]
            },{
               "score":5,
               "cal":5,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":3,
               "rank":213,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":220,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Poire,_x_TYPE.Yellow]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":7,
               "rank":108,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Small,_x_TYPE.§!}5\t\x01§]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":206,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":202,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":5,
               "\x0e-EY\x01":1,
               "rank":121,
               "tags":[_x_TYPE.Red,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Sugar]
            },{
               "score":20,
               "cal":20,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":226,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Yellow]
            },{
               "score":-10,
               "cal":10,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":111,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":3,
               "rank":95,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":132,
               "tags":[_x_TYPE.Small,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":10,
               "rank":83,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Yellow,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":137,
               "tags":[_x_TYPE.Orange,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":0,
               "vit":10,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":174,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":20,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":134,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Green]
            },{
               "score":5,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":92,
               "tags":[_x_TYPE.Small,_x_TYPE.Blue,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":1,
               "rank":157,
               "tags":[_x_TYPE.Nut]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":136,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":119,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Orange]
            },{
               "score":30,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":10,
               "rank":166,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":15,
               "cal":5,
               "vit":15,
               "sta":15,
               "\x0e-EY\x01":1,
               "rank":196,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Green,_x_TYPE.Long,_x_TYPE.Yellow]
            },{
               "score":15,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":127,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Green]
            },{
               "score":5,
               "cal":0,
               "vit":10,
               "sta":7,
               "\x0e-EY\x01":30,
               "rank":40,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Pink]
            },{
               "score":10,
               "cal":5,
               "vit":15,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":169,
               "tags":[_x_TYPE.Flower]
            },{
               "score":5,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":10,
               "rank":287,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Small,_x_TYPE.Green]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":69,
               "tags":[_x_TYPE.Green,_x_TYPE.Sugar]
            },{
               "score":20,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":87,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Alien,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":233,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":5,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":103,
               "tags":[_x_TYPE.Leaf,_x_TYPE.Courge,_x_TYPE.Sugar,_x_TYPE.Blue]
            },{
               "score":10,
               "cal":15,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":165,
               "tags":[_x_TYPE.Small,_x_TYPE.Nut]
            },{
               "score":25,
               "cal":40,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":240,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Nut]
            },{
               "score":15,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":66,
               "tags":[_x_TYPE.Red,_x_TYPE.Leaf,_x_TYPE.Apple,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":94,
               "tags":[_x_TYPE.Red,_x_TYPE.§!}5\t\x01§,_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Sugar]
            },{
               "score":5,
               "cal":5,
               "vit":20,
               "sta":5,
               "\x0e-EY\x01":2,
               "rank":150,
               "tags":[_x_TYPE.Long,_x_TYPE.Courge,_x_TYPE.Blue,_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":10,
               "vit":5,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":219,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Pink]
            },{
               "score":5,
               "cal":10,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":5,
               "rank":62,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Orange]
            },{
               "score":10,
               "cal":10,
               "vit":0,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":55,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Red,_x_TYPE.Long,_x_TYPE.Courge]
            },{
               "score":10,
               "cal":10,
               "vit":20,
               "sta":10,
               "\x0e-EY\x01":2,
               "rank":114,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.§1\x17E\x0e\x01§,_x_TYPE.Pink]
            },{
               "score":-10,
               "cal":10,
               "vit":10,
               "sta":10,
               "\x0e-EY\x01":1,
               "rank":145,
               "tags":[_x_TYPE.Sugar]
            },{
               "score":10,
               "cal":15,
               "vit":30,
               "sta":10,
               "\x0e-EY\x01":3,
               "rank":61,
               "tags":[_x_TYPE.Sugar,_x_TYPE.Leaf,_x_TYPE.Small]
            },{
               "score":-1,
               "cal":8,
               "vit":0,
               "sta":15,
               "\x0e-EY\x01":1000,
               "rank":180,
               "tags":[_x_TYPE.Shit,_x_TYPE.Sugar]
            }];
         }
         if(!Unserializer.init__)
         {
            Unserializer.init__ = true;
            Unserializer.DEFAULT_RESOLVER = Type;
         }
         if(!§\x12s}r§.init__)
         {
            §\x12s}r§.init__ = true;
            _loc2_ = Mods.extract("6870d93ba2a5b442c7cbd120ae1485dc",[Boot.__unprotect__("desc"),Boot.__unprotect__("fruit"),Boot.__unprotect__("name")],[]);
            §\x12s}r§.TEXT = _loc2_;
         }
         if(!Data.init__)
         {
            Data.init__ = true;
            _loc2_ = Mods.extract("e46abf40e865dd2492a7843ceda578be",[Boot.__unprotect__("\x0e-EY\x01"),Boot.__unprotect__("id"),Boot.__unprotect__("mojo"),Boot.__unprotect__("multi"),Boot.__unprotect__("time")],[_CardType]);
            Data.CARDS = _loc2_;
            Data.TEXT = §\x12s}r§.TEXT;
            Data.§\t;\x1cH\x02§ = [_CardType.TRAINING,_CardType.MAGNET,_CardType.CRYSTAL_BALL,_CardType._x_WINDFARM_SMALL,_CardType.POTION_BLUE,_CardType.SCISSOR,_CardType.HOURGLASS,_CardType.SALT];
            Data._x_quetes = [_CardType.FEATHER,_CardType.TONGUE,_CardType._x_MASSACRE,_CardType.LOUD_SPEAKER,_CardType.RAINBOW,_CardType.§N\x03L\x03§];
         }
         if(!Lang.init__)
         {
            Lang.init__ = true;
            Lang.§\x0b\x1a7u\x01§ = "Vous ne pouvez pas atteindre 6 points" + Lang.§[y\n*\x01§ + " de mojo avec vos cartes actives" + Lang.§[y\n*\x01§ + ".\nToute vos cartes seront\n réactivées à minuit !\n\nVous pouvez également acheter des" + Lang.§[y\n*\x01§ + " cartes supplémentaires en boutique:";
            Lang.§9X~g§ = ["Le serpent suis le pointeur de la " + Lang.col("souris",Lang.WHITE) + ". Utiliser le " + Lang.col("clic gauche",Lang.WHITE) + " pour accélérer.","Flèche " + Lang.col("haut bas gauche",Lang.WHITE) + " et " + Lang.col("droite",Lang.WHITE) + " pour choisir l\'orientation du serpent.\n" + Lang.col("Barre espace",Lang.WHITE) + " pour accélérer.","Flèches " + Lang.col("gauche",Lang.WHITE) + " et " + Lang.col("droite",Lang.WHITE) + " de votre clavier pour faire pivoter le serpent.\nFlèche " + Lang.col("haut",Lang.WHITE) + " pour accélérer.",Lang.col("Concentrez vous",Lang.WHITE) + " sur un point de l\'arène pour que le serpent s\'y dirige.\nPour accélérer, concentrez-vous " + Lang.col("plus fort",Lang.WHITE) + "."];
            Lang.§6\x1d)m\x03§ = "Il te faut au moins " + Lang.col("%1","#FF6666") + " cartes pour pouvoir entrer dans le bazar !!";
            Lang.§;eq,§ = "Chaque jour des tournois de %1 joueurs sont lancés entre %2 heures et %3 heures.\n\nLe tournoi est actuellement " + Lang.col("fermé",Lang.WHITE) + ", prochain tournoi dans %4 ";
            Lang.§xBj?\x01§ = Lang.col("Règles du tournoi",Lang.WHITE) + " : Chaque joueur reçoit " + Lang.col("10 nouvelles cartes","#FF0088") + ", il en choisit " + Lang.col("une","#FF0088") + " puis fait passer le paquet à son voisin. On répète l\'opération jusqu\'à épuisement des cartes. Chacun joue ensuite autant de parties qu\'il le peut avec les 10 cartes choisies, puis " + Lang.col("le plus haut score","#FF0088") + " emporte le tournoi.\nUne partie de tournoi peut contenir entre " + Lang.col("1","#88DD00") + " et " + Lang.col("6 pts","#88DD00") + " de mojo.\nChacun repart avec ses 10 cartes et les 3 meilleurs reçoivent un prix.";
            Lang.§ U\x05\x18\x01§ = "Le tournoi a été " + Lang.col("annulé","#FF5555") + " !\n" + Lang.col("(C\'est un scandale)","#88DD00") + "\nVos " + Data.§gtE\f§ + " jetons ont été remboursés.";
         }
         if(!Main.init__)
         {
            Main.init__ = true;
            Main.rec = §h\x05\x02\x02§.getBytes("replay");
         }
         if(!Element.init__)
         {
            Element.init__ = true;
            Element.NEUTRAL_CT = new ColorTransform(1,1,1,1,0,0,0,0);
            Element.§#\x05\x02§ = new Matrix();
         }
         if(!Protocol.init__)
         {
            Protocol.init__ = true;
            Protocol.CODES = Lambda.array(Lambda.map(Type.getEnumConstructs(Code),function(param1:Function, param2:*):Function
            {
               var f:Function = param1;
               var a1:* = param2;
               return function(param1:String):*
               {
                  return f(a1,param1);
               };
            }(Reflect.field,Code)));
         }
         Main.main();
      }
   }
}
